### ISSUE TITLE
exec 方法抛异常

### ISSUE THREAD

**Issue by heiheiLqq** [alipay/alipay-sdk#4]
const AlipaySDK = require('alipay-sdk').default;
const fs = require('fs')

const alipaySdk = new AlipaySDK({
appId: '2018081661053647',
privateKey: fs.readFileSync(__dirname + '/../secretKey/private-key.pem', 'ascii'),
alipayPublicKey: fs.readFileSync(__dirname+'/../secretKey/public-key.pem', 'ascii'),
});
async function getAccessToken (auth_code,refreshToken) {
alipaySdk.exec('alipay.system.oauth.token', {
grantType: 'authorization_code',
code: auth_code,
refreshToken: ''
}).then(res => {
console.log(res);
}).catch((err) => {
console.log(err);
});
}

报异常

TypeError: [AlipaySdk]exec error
at WeakMap.set (native)
at mapObj (/Users/zhuangzihao/i-counting/customer_api/node_modules/map-obj/index.js:23:7)
at camelCaseConvert (/Users/zhuangzihao/i-counting/customer_api/node_modules/camelcase-keys/index.js:16:9)
at module.exports (/Users/zhuangzihao/i-counting/customer_api/node_modules/camelcase-keys/index.js:39:9)
at config.urllib.request.then (/Users/zhuangzihao/i-counting/customer_api/node_modules/alipay-sdk/lib/alipay.js:251:52)
at 
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by myliweihao** [comment]
我也遇到这个问题，请问解决了吗？

**Comment by leoner** [comment]
+1

![image](https://user-images.githubusercontent.com/546535/44576211-8adb7e00-a7c0-11e8-806e-1f60b46127ef.png)

重现就是比如把key 写错啥的, 开放平台会返回一个错误, 这个时候, 解析这里就报错了.

**Comment by leoner** [comment]
比如这个错误返回了, 肯定解析不出来

```
{"error_response":{"code":"40002","msg":"Invalid Arguments","sub_code":"isv.code-invalid","sub_msg":"授权码code无效"
```

**Comment by leoner** [comment]
@tudou527 尽快帮忙修复吧, 估计后面碰到这个错误的人会很多.

**Comment by tudou527** [comment]
https://github.com/alipay/alipay-sdk/commit/9107cebb6e1727997a86e2162e725720c67dfa92

**Comment by heiheiLqq** [comment]
fork 一份 这么改
alipay.js  256行
if (validateSuccess) 改成 if(validateSuccess && data)
